AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.11

  SAM Template for Laurus Education Customer Service Agent

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120 # timeout after two minutes

Resources:
  ThreadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  MainFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      ThreadsTableConnector:
        Properties:
          Destination:
            Id: ThreadsTable
          Permissions:
            - Read
            - Write
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy: 
            TableName: !Ref ThreadsTable  # Grant Lambda full CRUD access to ThreadsTable
      Events:
        General:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+} # Routes are handled by Mangum adapter inside in the handler
            Method: ANY
      Environment:
        Variables:
          WHATSAPP_ACCESS_TOKEN:
          WHATSAPP_API_VERSION: v18.0
          WHATSAPP_APP_ID:
          WHATSAPP_APP_SECRET:
          PHONE_NUMBER_ID:
          WHATSAPP_VERIFY_TOKEN:
          OPENAI_API_KEY:
          OPENAI_ASSISTANT_ID:
          GOOGLE_API_KEY:
          GOOGLE_CSE_ID:
          TABLE_NAME: !Ref ThreadsTable # Name of the DynamoDB table created above
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.11-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ChatInvokeURL:
    Description: "API Gateway endpoint URL for regular chat endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chat"

  ApiGatewayWebhookURL:
    Description: "API Gateway endpoint URL for Whatsapp webhook"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook"

  DynamoDBTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref ThreadsTable

  MainFunction:
    Description: "Main Lambda Function ARN"
    Value: !GetAtt MainFunction.Arn
